apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice1
  name: microservice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice1
  strategy: {}
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
        - name: microservice1
          image: 012345678901.dkr.ecr.eu-west-1.amazonaws.com/microservice1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 800m
              memory: 1536Mi
            requests:
              cpu: 200m
              memory: 1536Mi
      restartPolicy: Always
