apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice1
  name: microservice1
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: microservice1
