apiVersion: v1
kind: Service
metadata:
  name: microservice2
  namespace: microservice2
  labels:
    app: microservice2
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: microservice2
