apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: develop

bases:
  - ../base/microservice1
  - ../base/microservice2

patchesStrategicMerge:
  - microservice1/deployment.yaml
  - microservice2/deployment.yaml
